### ISSUE TITLE
Allow definition of transient base oscillations in formula

### ISSUE THREAD

**Issue by CodeLionX** [HPI-Information-Systems/gutentag#10]
Example configuration:

```yaml
timeseries:
  - name: "mytest"
    length: 1000
    base-oscillations:
      - kind: "formula"
        formula:
          base:
            kind: "ecg"
            frequency: 1
            variance: 0
          operation:
            kind: "*"
            operand: 1
```
