### ISSUE TITLE
Add post-processing options

### ISSUE THREAD

**Issue by CodeLionX** [HPI-Information-Systems/gutentag#11]
Add configuration options to post-process (each individual channel) of a time series.

Post-processing options include:

- smoothing using convolution along t
- segment smoothing (smooth different parts of the time series differently)
- scaling and standardization (MinMax, z-score, ...)

Example configuration:

```yaml
timeseries:
  - name: "mytest"
    length: 1000
    base-oscillations:
      - kind: "sine"
        frequency: 1
      [...]
    anomalies:
      - position: "beginning"
        [...]
    post-processing:
      - channel: 0
        kind: "smoothing"
        factor: 2.0
```
