### ISSUE TITLE
Add a smooth transition to the anomaly API

### ISSUE THREAD

**Issue by CodeLionX** [HPI-Information-Systems/gutentag#13]
Some existing anomaly kinds use smooth transitions. We should allow all (except extremum) anomalies to do this, and therefore move it to the anomaly itself instead of the anomaly kind.

Example configuration:

```yaml
timeseries:
  - name: "test"
    base-oscillations:
      - kind: "sine"
    anomalies:
      - position: beginning
        length: 100
        transition-window: 10  # <--
        kinds:
          - kind: "amplitude"
            amplitude_factor: 2
```
