### ISSUE TITLE
New anomaly: Normalize

### ISSUE THREAD

**Issue by CodeLionX** [HPI-Information-Systems/gutentag#14]
Normalization anomalies can be constructed by combining mean and amplitude anomaly kinds, however, this is difficult to achieve. Add a new anomaly kind that allows to specify the way a subsequence should be normalized. Normalization options:

- normalize-z
- normalize-minmax
- normalize-median
- normalize-mean
- normalize-logistic
- normalize-tanh

Example configuration:

```yaml
timeseries:
  - name: "test"
    base-oscillations:
      - kind: "sine"
    anomalies:
      - position: beginning
        length: 100
        kinds:
          - kind: "normalize-minmax"
            min: 0
            max: 1
```
