### ISSUE TITLE
Use existing TS file as base oscillation

### ISSUE THREAD

**Issue by CodeLionX** [HPI-Information-Systems/gutentag#9]
Use an existing time series as base oscillation for a new dataset. This allows injecting our anomalies into existing time series. The file must be formatted in our canonical file format.

GutenTAG tries to parse the ground truth (label) information to prevent anomaly overlaps.

Example configuration:

```yaml
timeseries:
  - name: "test"
    base-oscillations:
      - kind: file
        path: path/to/file.csv
        channel: 0
```
